name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set-up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build linux binary
        run: go build -o build_linux/deplog

      - name: Zip linux binary
        uses: thedoctor0/zip-release@master
        with:
          directory: build_linux/
          type: 'zip'
          filename: 'deplog-linux64.zip'

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build_linux/deplog-linux64.zip
